window.variables = require("./variables.js")
require("./materialize.min.js")
window.DOMStuff = require("./DOMStuff.js")
window.Format = require("./Format.js")
require("./Game.js")
require("./Chat.js")